name: _publish_base

on:
  workflow_call:
    inputs:
      docker_registry:
        required: true
        type: string
      dockerfile_path:
        required: true
        type: string
      project_path:
        required: true
        type: string
      image_name:
        required: true
        type: string
      image_tag:
        required: false
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_LOGIN: peresheinis
      GITHUB_TOKEN: ${{secrets.peresheinis_PAT}}
      
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: lebedeffdeveloper
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Call publish script
        run: |
          chmod +x scripts/build_and_push_base.sh 
          scripts/build_and_push_base.sh ${{ inputs.project_path }} ${{ inputs.image_name }} ${{ inputs.docker_registry }} ${{ inputs.dockerfile_path }} ${{ inputs.image_tag }}
        shell: bash